<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<ServerGarbageCollection>true</ServerGarbageCollection>
	<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewGen\**" />
    <EmbeddedResource Remove="NewGen\**" />
    <None Remove="NewGen\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CardGame.Core\CardGame.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Decks\" />
    <Folder Include="Data\Cards\" />
    <Folder Include="Evolution\Ev\Core\Evolution\" />
    <Folder Include="Evolution\Ev\Core\Genetics\" />
    <Folder Include="Evolution\Ev\Core\Models\" />
    <Folder Include="Evolution\Ev\Game\Analysis\" />
    <Folder Include="Evolution\Ev\Game\Simulation\" />
    <Folder Include="Evolution\Ev\Analytics\" />
    <Folder Include="Evolution\Ev\Persistance\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\Cards\cards.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Decks\starter_deck.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
